# logging.level.org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: e50b7a8acd83a7622d63
            client-secret: Visit https://github.com/settings/developers to make new id & secret

